name: prueba
description: "Esta es una prueba técnica, desarrollo en Flutter."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.4.1
  path: ^1.9.0
  get_it: ^8.0.2
  cupertino_icons: ^1.0.8
  mobx: ^2.4.0
  flutter_mobx: ^2.2.1+1
  build_runner: ^2.4.13
  sqflite_common_ffi: ^2.3.4+3
  image_picker: ^1.1.2
  provider: ^6.1.2
  permission_handler: ^11.3.1
  geolocator: ^9.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.5
  mobx_codegen: ^2.0.7

  flutter_lints: ^4.0.0


flutter:


  uses-material-design: true


